[package]
name = "galvanizer_store"
version = "0.1.0"
edition = "2024"

[dependencies]
snap = "1.1.1"
galvanizer_config = { path = "../galvanizer_config" }
sha2 = "0.10.9"
log = "0.4.28"
env_logger = "0.11.8"
walkdir = "2.5.0"
toml = { version = "0.9.8", features = ["serde"] }
base64 = "0.22.1"
dashmap = "6.1.0"

[dependencies.chrono]
version = "0.4.42"
features = ["serde"]

[dependencies.serde]
version = "1.0.228"
features = ["derive"]

[dev-dependencies]
map-macro = "0.3.0"
tempdir = "0.3.7"
